name: Build Idena Contract Runner

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.17.x]
    runs-on: ubuntu-20.04

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Get Sources
        uses: actions/checkout@v2

      - name: Build
        run: go build